/*
========================================================================================================================
EDA (Exploratoty Data Analysis)
========================================================================================================================
Script Purpose:
 1) Database Exploration
 2) Dimension Exploration
 3) Date Exploration
 4) Measure Exploration
 5) Magnitude Analysis
 6) Ranking Analysis
*/


/* 1) Database Exploration with 'INFORMATION_SCHEMA' */

SELECT *
FROM INFORMATION_SCHEMA.COLUMNS
WHERE table_name = 'dim_customers'


/* 2) Dimension Exploration
	  - Identifying the unique values or categories in each dimension
	  - Recognizing how data might be grouped or segmented, which is useful for later analysis */

SELECT DISTINCT country
FROM gold.dim_customers

SELECT DISTINCT marital_status
FROM gold.dim_customers

SELECT DISTINCT gender
FROM gold.dim_customers


/* 3) Date Exploration
	  - Identify the earliest and lasted dates (boundaries)
	  - To understand the range of historical data */

SELECT MIN(order_date), MAX(order_date)
FROM gold.fact_sales


/* 4) Measure Exploration 
	  - To calculate aggregated metrics (e.g., totals, averages) for insights */

-- Find total sales
SELECT SUM(sales_amount) as total_sales FROM gold.fact_sales

-- Find how many items are sold
SELECT SUM(quantity) as total_quantity FROM gold.fact_sales

-- Find the average selling price
SELECT AVG(price) as avg_price FROM gold.fact_sales

-- Find the total number of orders
SELECT COUNT(order_number) as total_orders FROM gold.fact_sales
SELECT COUNT(DISTINCT order_number) as total_orders FROM gold.fact_sales

-- Find the total number of products
SELECT COUNT(product_name) as total_products FROM gold.dim_products
SELECT COUNT(DISTINCT product_name) as total_products FROM gold.dim_products

-- Find the total number of customer that has placed an order
SELECT COUNT(DISTINCT customer_key) as total_customers FROM gold.fact_sales

-- Find the total number of customer
SELECT COUNT(customer_key) as total_customers FROM gold.dim_customers

-- Generate a Report that shows all key metrics of the business
SELECT 'Total Sales' as measure_name, SUM(sales_amount) as measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total Quantity' as measure_name, SUM(quantity) as measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Average Price' as measure_name, AVG(price) as measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total Orders' as measure_name, COUNT(DISTINCT order_number) as measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total Products' as measure_name, COUNT(DISTINCT product_name) as measure_value FROM gold.dim_products
UNION ALL
SELECT 'Total Customers' as measure_name, COUNT(DISTINCT customer_key) as measure_value FROM gold.dim_customers


/* 5) Magnitude Analysis
	  - For understanding data distribution with each categories */

-- Find total customers by countries
SELECT country,
	   COUNT(customer_key) as total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC

-- Find total customers by gender
SELECT gender,
	   COUNT(customer_key) as total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC

-- Find total products by category
SELECT category,
	   COUNT(product_key) as total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC

-- What is the average costs in each category
SELECT category,
	   AVG(cost) as average_cost
FROM gold.dim_products
GROUP BY category
ORDER BY average_cost DESC

-- What is the total revenue generated for each category
select dp.category,
	   SUM(sales_amount) as total_sales 
FROM gold.fact_sales as f
LEFT JOIN gold.dim_products as dp ON f.product_key = dp.product_key
GROUP BY dp.category

-- Find total revenue is generated by each customer
select dc.customer_key,
	   SUM(f.sales_amount) as total_sales 
FROM gold.fact_sales as f
LEFT JOIN gold.dim_customers as dc ON f.customer_key = dc.customer_key
GROUP BY dc.customer_key
ORDER BY total_sales DESC

-- What is the distribution of sold items across countries
SELECT dc.country,
	   SUM(f.quantity) as total_sold_items
FROM gold.fact_sales as f
LEFT JOIN gold.dim_customers as dc ON f.customer_key = dc.customer_key
GROUP BY dc.country
ORDER BY total_sold_items DESC


/* 6) Ranking Analysis
	  - Order the values of dimension by measure
	  - Top N performers & Bottom N performers */
 
 -- Which 5 products generate the highest revenue?
 SELECT TOP 5
		p.product_name,
	    SUM(f.sales_amount) as total_sales
 FROM gold.fact_sales as f
 LEFT JOIN gold.dim_products as p ON f.product_key = p.product_key
 GROUP BY p.product_name
 ORDER BY total_sales DESC

  -- Which 5 products generate the lowest revenue?
 SELECT TOP 5
		p.product_name,
	    SUM(f.sales_amount) as total_sales
 FROM gold.fact_sales as f
 LEFT JOIN gold.dim_products as p ON f.product_key = p.product_key
 GROUP BY p.product_name
 ORDER BY total_sales

